name = "Turtland Create"
author = "JujuBoyo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b06fe0b54c7aba1b9e6003bd790dea24a7dcdb3537736eb763bca7503503374"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
