name = "Turtland Create"
author = "JujuBoyo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b5e4fad6aaa47120342945deffe520012fc32fb0d2d531ab74e73e3d79dadc2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
