name = "Turtland Create"
author = "JujuBoyo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "427eabe7528f12a1e56dce07c000391e5a8f1ee73d108b272be3c1db955f6574"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
